name: Deploy to Lightsail
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ardeveloper123
          password: MIIEpAIBAAKCAQEAwqKpPR6XyT2KEA5Qsq/4YcVjxK81DbRID+joc3fAOciClJYV+udslacz5LRCMtgUX7/XvpThDem62U2eYn9oQhc0iUT2xhSGaRTLmRpJvVo+M6ks3B2vRpYzuMEXcidz4oDA2G4reAq+Alm3+vvcmtA76Zm0AQRXuN+bSyEFLzyrwZHkDvxs7aWhRX3RlS/iYqOnJubKZZ5pieXl1XAb18rW8MISRO/hbEFpysv69emWS2Pygn8EXX9VhD7eNfbvS3NvRN/6T59MK3vTd3fjoIXXH50iKrmLkO7o0AT5XOu9GuRBdZFY/BWQrg4qK7NhPyen1QBmOahKoUgEwliVyQIDAQABAoIBACNoF8VolVAkg8Mb944p+NNAZz/WZ55Ql3NdeTvYIv3f/fEtxF3aT6SBwCzwpcI+EKbCbWrcBnzTcgwp1JAygTLUqdf21bV+8lyXTdpSL+vkSMB5HBIGzGXY2RvY9HzttGUV6v70O7AgtCQVUiS0QJNhIiUCsv4kXhjhhIyMOzc2To9JEKuJURSA+yEAlIGbc4jUmwpd9AW3ErAI8HmlymVMmyOOec8HzyAJpSUD4nFdjGxpXAfsvbse9z3US8gLzBxlKVuhTwWFfhG7CijmEsbNkFEqYDpPYHawg3+2FUoremixa8FL4ObxXHa/Wi+y5v5xSoUHtcZfN1Ot8uYQBWkCgYEA+MpH4o5Ykv8/DOBxfM8i8mmKomKVTn+MasKL9JMu4NWaU9Pvdg+HBYMKtoIVy94SkO8ytrZeOI4roYLE6mFMi7PCZkf5VMkHaGoyU0tD5Ch6NQKPpuzFz0hz4Vnw6BnS9gqSdAkSNCp6SNfomENWcRoVBsB0UiRHs0Wied5QXQ8CgYEAyEaeOTu2WQMDbPiHxJm7Ot1PDBb3uAesYHTnRCGyOFKQA6VbEAtJuE/sa+/VrMTIbIRO8U0/5XOUaioy7a6f6CmCGcNA3Jt/NGGJfgbV0yFJn3pm6FpDCi93EvdEtBtw+dJwMs2w3u2k/8Vm3tgQLdQ+HNfcHLa/FBiqrwIID6cCgYEAj5NFCuT1DtgIzeiU9d8gHt9zpyTXX3bSVSYy2JE8A3qh1nC/h9WMKU0nmI3YAFAHTOcN0E3McDzzxwCNnWlLYG/750TwCdL92G843cLYyknlxMPWnRGVUntQjKN4GKoWifEt9ZLqk3pUGceoLn7l2t2fdscIGgNf8YBlNIlsvVcCgYAHEX76FCJuZ83SJb9c7/QMsszcZ18czqCF0vpqjCnnFPriNg7NtShH6gI1GQTYkSVltxG2MHzF01t0l8KuYtBf+D8QO7TpVE+cAKlCmmknh3A6wa4qGy1siZpRQArbtHA7UPMGx/2rEIYXRNdJnCSOCYSbrf6lwMljoy869/5i1wKBgQCC2SrKuOTjrcgpmOVOTxchNc+3/JxmbYDUdjKSHrpYEcTFr0kuoUSv78QYEcuYK3c31tMY+pCw5p7dVIx0RkKltDiBhSWQojgUwaBg0xvuYs5MbLaJJd9Fw1fb/xGWLXI1Vq/rJzwQ/nw0pba8tHZubbutpkQdXV4QRwbebY1Eag==

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}

      - name: Deploy to Lightsail via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}
            docker stop node_app || true
            docker rm node_app || true
            docker run -d --restart=always \
              -e NODE_ENV=production \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}" \
              -e CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}" \
              -e CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}" \
              -p 3000:3000 \
              --name node_app ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}
